# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surve',
            fields=[
                ('ref_no', models.IntegerField(primary_key=True, serialize=False)),
                ('house_owner', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
            ],
        ),
    ]
