# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surve',
            name='ref_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
