# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurvey', '0002_auto_20180513_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surve',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
